### ISSUE TITLE
[Todo] Initial tasks

### ISSUE THREAD

**Issue by Akilan1999** [PeernetOfficial/Peernet-test-framework#1]
- [x] Manual setup 
- [x] Spawning nodes locally.
- [x] Setting root nodes automatically.
- [x] Able add and remove configurations from a config file.
